# Generated by Django 5.1.4 on 2025-03-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_language', models.CharField(choices=[('Malayalam', 'Malayalam'), ('Tamil', 'Tamil'), ('Kannada', 'Kannada'), ('Hindi', 'Hindi'), ('English', 'English')], max_length=100)),
                ('director', models.CharField(max_length=60)),
                ('genre', models.CharField(choices=[('horror', 'horror'), ('war', 'war'), ('apocalypse', 'apocalypse'), ('science fiction', 'science fiction'), ('mystery', 'mystery'), ('comedy', 'comedy')], max_length=100)),
            ],
        ),
    ]
