# Generated by Django 5.1.4 on 2025-03-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_review_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_model',
            old_name='movie_id',
            new_name='movie_name',
        ),
        migrations.RenameField(
            model_name='review_model',
            old_name='user_id',
            new_name='reviewer',
        ),
        migrations.AlterField(
            model_name='movie_model',
            name='genre',
            field=models.CharField(choices=[('horror', 'horror'), ('action', 'action'), ('war', 'war'), ('apocalypse', 'apocalypse'), ('science fiction', 'science fiction'), ('mystery', 'mystery'), ('comedy', 'comedy')], max_length=100),
        ),
    ]
