# Generated by Django 5.1.4 on 2025-03-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0003_rename_movie_id_review_model_movie_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_model',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
