# Generated by Django 5.1.4 on 2025-03-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0007_alter_movie_model_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_model',
            name='image',
        ),
    ]
