# Generated by Django 5.1.4 on 2025-03-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0008_remove_movie_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_model',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
