# Generated by Django 5.1.4 on 2025-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0010_alter_movie_model_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_model',
            old_name='movie_name',
            new_name='movie_id',
        ),
        migrations.AlterField(
            model_name='movie_model',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
