# Generated by Django 5.1.4 on 2025-03-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0011_rename_movie_name_review_model_movie_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_model',
            name='movie_id',
        ),
    ]
